import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { use } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const isDark = use(new Promise(async (res) => {
    const cookieStore = await cookies();
    const theme = cookieStore.get("theme")?.value;
    if (theme === "dark") {
      res(true);
    } else if (theme === "light") {
      res(false);
    } else {
      res(false);
    }
  }));

  return (
    <html lang="en" className={`${isDark ? "dark" : ""}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
